import type { Icon, IconProps } from "@phosphor-icons/react";
import {
  ArrowsClockwiseIcon,
  ArrowsLeftRightIcon,
  BellRingingIcon,
  ChalkboardTeacherIcon,
  ChatsCircleIcon,
  ChatTextIcon,
  CirclesThreeIcon,
  ClockIcon,
  CubeFocusIcon,
  DeviceMobileIcon,
  EnvelopeSimpleIcon,
  FilmStripIcon,
  FirstAidIcon,
  HandPointingIcon,
  HashStraightIcon,
  LayoutIcon,
  ListNumbersIcon,
  MagicWandIcon,
  MagnifyingGlassIcon,
  MaskHappyIcon,
  MicrophoneIcon,
  MonitorPlayIcon,
  NotePencilIcon,
  PencilLineIcon,
  PillIcon,
  ProhibitIcon,
  RankingIcon,
  ScalesIcon,
  ShieldCheckIcon,
  ShoppingBagIcon,
  SignpostIcon,
  SmileySadIcon,
  SparkleIcon,
  StarIcon,
  TextTIcon,
  TextStrikethroughIcon,
  ThumbsDownIcon,
  UserCircleIcon,
  UserFocusIcon,
  UsersThreeIcon,
  VideoCameraIcon,
  WarningIcon,
} from "@phosphor-icons/react";

import { normalizeFormatId } from "@/content/formats";

/** Un icono distinto por formato — sin repetir dentro de la taxonomía. */
const FORMAT_ICONS: Record<string, Icon> = {
  "x-razones": ListNumbersIcon,
  "historia-instagram": DeviceMobileIcon,
  "nosotros-vs-ellos": ArrowsLeftRightIcon,
  "diagrama-venn": CirclesThreeIcon,
  "no-compres-esto": ProhibitIcon,
  "nota-iphone": NotePencilIcon,
  "captura-chat": ChatsCircleIcon,
  pizarra: ChalkboardTeacherIcon,
  "cupos-limitados": BellRingingIcon,
  "pedimos-disculpas": SmileySadIcon,
  "testimonio-cliente": UserCircleIcon,
  "lo-nuevo-vs-lo-viejo": ArrowsClockwiseIcon,
  "ultima-hora": ClockIcon,
  transformacion: SparkleIcon,
  "estilo-reddit": ChatTextIcon,
  "en-caso-de-emergencia": FirstAidIcon,
  "busqueda-google": MagnifyingGlassIcon,
  "problema-vs-solucion": ScalesIcon,
  "efecto-secundario": PillIcon,
  "oferta-combo": ShoppingBagIcon,
  "titular-con-dato": HashStraightIcon,
  garabato: PencilLineIcon,
  "captura-email": EnvelopeSimpleIcon,
  "no-seas-ese-que": HandPointingIcon,
  resenas: StarIcon,
  "texto-sobre-la-piel": TextTIcon,
  "podcast-ia": MicrophoneIcon,
  "tier-list": RankingIcon,
  "cero-estrellas": ThumbsDownIcon,
  "green-screen": VideoCameraIcon,
  "x-senales": SignpostIcon,
  "mito-vs-realidad": MaskHappyIcon,
  "problemas-tachados": TextStrikethroughIcon,
  "lo-que-podes-evitar": ShieldCheckIcon,
  advertencia: WarningIcon,
  "grabacion-pantalla": MonitorPlayIcon,
  "motion-graphics": CubeFocusIcon,
  "video-ia": MagicWandIcon,
  "texto-cinetico": TextTIcon,
  "talking-head": UserFocusIcon,
  entrevista: UsersThreeIcon,
  vlog: FilmStripIcon,
};

export function getFormatIcon(formatId: string): Icon {
  return FORMAT_ICONS[normalizeFormatId(formatId)] ?? LayoutIcon;
}

export function FormatIcon({
  formatId,
  className,
  ...props
}: { formatId: string } & IconProps) {
  const IconComponent = getFormatIcon(formatId);
  return <IconComponent className={className} {...props} />;
}
