import { extendedCompetitorCatalog } from "@/content/competitor-catalog-extensions";
import type { CompetitorInspiration } from "@/content/competitor-inspirations";
import { getCompetitorMercantisMarkets } from "@/content/competitor-rankings";
import { COMPETITOR_FILTER_COUNTRIES } from "@/content/competitor-view";

type CompetitorSeed = Omit<CompetitorInspiration, "operatingCountries"> & {
  /** Países extra además de los del ranking (ej. presencia oficial documentada). */
  extraCountries?: string[];
};

function buildOperatingCountries(seed: CompetitorSeed): string[] {
  const filterSet = new Set<string>(COMPETITOR_FILTER_COUNTRIES);
  const fromMarkets = getCompetitorMercantisMarkets(seed.id);
  const fromExtra = (seed.extraCountries ?? []).filter((c) => filterSet.has(c));
  const fromOrigin = filterSet.has(seed.originCountry)
    ? [seed.originCountry]
    : [];

  return [...new Set([...fromMarkets, ...fromExtra, ...fromOrigin])];
}

const SEEDS: CompetitorSeed[] = [
  // —— En radar previo (sin ranking por país) ——
  {
    id: "minificando-ai",
    name: "Minificando.ai",
    summary: "Sistemas de gestión a medida para PyMEs. Todo el negocio en una pantalla.",
    originCountry: "Argentina",
    extraCountries: ["Argentina"],
    instagramUrl: "https://www.instagram.com/minificando.ai",
    websiteUrl: "https://minificando.ai",
    documentId: "minificando-ai",
    note: "Buena estrategia de contenido: highlights por cliente, casos de éxito y reels.",
  },
  {
    id: "calipso",
    name: "Calipso",
    summary: "ERP cloud con IA (grupo Visma). Facturación, inventario y agentes para PyMEs.",
    originCountry: "Argentina",
    extraCountries: ["Argentina", "Chile", "Perú", "Colombia", "México", "España"],
    websiteUrl: "https://www.calipso.com",
    instagramUrl: "https://www.instagram.com/calipso_visma",
    note: "Parte de Visma. Presencia multipaís en LATAM y España.",
  },
  {
    id: "ventasxmayor",
    name: "VentasxMayor",
    summary: "eCommerce B2B para mayoristas: catálogos privados, precios por cliente y feeds.",
    originCountry: "Argentina",
    extraCountries: ["Argentina", "Chile", "México"],
    websiteUrl: "https://www.ventasxmayor.com.ar",
    instagramUrl: "https://www.instagram.com/ventasxmayor",
    tiktokUrl: "https://www.tiktok.com/@ventasxmayor.ecommerce",
  },
  {
    id: "ecomm-app",
    name: "Ecomm-App",
    summary: "Gestión para sellers: facturación, stock y publicaciones de ML, Tiendanube y local.",
    originCountry: "Argentina",
    extraCountries: ["Argentina"],
    websiteUrl: "https://www.ecomm-app.com",
    instagramUrl: "https://www.instagram.com/ecommapp",
  },
  {
    id: "mesanube",
    name: "Mesanube",
    summary: "POS y comanda digital para gastronomía. ARCA incluida, mozos y monitor de cocina.",
    originCountry: "Argentina",
    extraCountries: ["Argentina"],
    websiteUrl: "https://mesanube.ar",
    instagramUrl: "https://www.instagram.com/mesanube",
    note: "Enfocado en gastronomía, no confundir con Gestión Nube.",
  },
  {
    id: "ayres-it",
    name: "Ayres IT",
    summary: "POS y ERP para gastronomía y cadenas. Integra delivery, WooCommerce y Tiendanube.",
    originCountry: "Argentina",
    extraCountries: ["Argentina", "Latinoamérica"],
    websiteUrl: "https://ayresit.ar",
    instagramUrl: "https://www.instagram.com/ayresit",
  },
  {
    id: "redi-rediredi",
    name: "Redi / RediRedi",
    summary: "Red de vendedores con catálogo digital e IA. WhatsApp e Instagram para vender.",
    originCountry: "Brasil",
    extraCountries: ["Brasil", "Latinoamérica"],
    websiteUrl: "https://site.rediredi.com",
    instagramUrl: "https://www.instagram.com/RediRediBrasil",
  },
  {
    id: "callbell-shop",
    name: "Callbell Shop",
    summary: "Tienda gratis para WhatsApp. Catálogo + sync con Meta (FB/IG). CRM de Callbell.",
    originCountry: "Francia",
    extraCountries: ["Internacional", "Latinoamérica"],
    websiteUrl: "https://www.callbell.shop",
    instagramUrl: "https://www.instagram.com/callbell.shop",
    tiktokUrl: "https://www.tiktok.com/@callbelloficial",
  },

  // —— Rankings LATAM sep 2026 ——
  {
    id: "tiendanube",
    name: "Tiendanube",
    summary: "Plataforma e-commerce líder en LATAM. Tienda online, pagos y envíos integrados.",
    originCountry: "Argentina",
    extraCountries: ["Brasil", "México"],
    websiteUrl: "https://www.tiendanube.com",
    instagramUrl: "https://www.instagram.com/tiendanube",
    note: "Opera oficialmente en AR, BR y MX. Presencia competitiva también en CL y CO.",
  },
  {
    id: "shopify",
    name: "Shopify",
    summary: "Plataforma global de e-commerce. Tienda, pagos, apps y omnicanal.",
    originCountry: "Canadá",
    websiteUrl: "https://www.shopify.com",
    instagramUrl: "https://www.instagram.com/shopify",
  },
  {
    id: "empretienda",
    name: "Empretienda",
    summary: "Tienda online sin comisiones por venta. Pagos, envíos y mayorista integrados.",
    originCountry: "Argentina",
    websiteUrl: "https://www.empretienda.com",
    instagramUrl: "https://www.instagram.com/empretiendaok",
  },
  {
    id: "treinta",
    name: "Treinta",
    summary: "Sistema de gestión para negocios: POS, inventario, catálogo y facturación. 7M+ negocios.",
    originCountry: "Colombia",
    extraCountries: ["Latinoamérica"],
    websiteUrl: "https://treinta.co",
    instagramUrl: "https://www.instagram.com/treintaco",
    note: "Presencia en 21 países. Referente regional clave para Mercantis.",
  },
  {
    id: "pedix",
    name: "Pedix",
    summary: "Tienda online + pedidos por WhatsApp sin comisiones. Facturación AFIP y logística.",
    originCountry: "Argentina",
    extraCountries: ["Venezuela"],
    websiteUrl: "https://info.pedix.app",
    instagramUrl: "https://www.instagram.com/pedix_ok",
    note: "AR, CL, CO, MX, UY, VE.",
  },
  {
    id: "pency",
    name: "Pency",
    summary: "Catálogo digital y tienda para WhatsApp. Pedidos, pagos y gestión simple.",
    originCountry: "Argentina",
    websiteUrl: "https://pency.app",
    instagramUrl: "https://www.instagram.com/pencyapp",
  },
  {
    id: "woocommerce",
    name: "WooCommerce",
    summary: "Plugin open-source de e-commerce para WordPress. Altamente personalizable.",
    originCountry: "Estados Unidos",
    websiteUrl: "https://woocommerce.com",
    instagramUrl: "https://www.instagram.com/woocommerce",
  },
  {
    id: "changuito",
    name: "Changuito",
    summary: "Tienda online argentina para PyMEs. Catálogo, WhatsApp y pagos locales.",
    originCountry: "Argentina",
    websiteUrl: "https://changuito.ar",
    instagramUrl: "https://www.instagram.com/changuito.ar",
  },
  {
    id: "dux",
    name: "Dux Software",
    summary: "ERP y gestión comercial para PyMEs argentinas. Stock, ventas y facturación.",
    originCountry: "Argentina",
    websiteUrl: "https://www.duxsoftware.com.ar",
    instagramUrl: "https://www.instagram.com/duxsoftware",
  },
  {
    id: "mercado-libre",
    name: "Mercado Libre / Mi Página",
    summary: "Marketplace líder + Mi Página para tienda propia dentro del ecosistema ML.",
    originCountry: "Argentina",
    extraCountries: ["Latinoamérica"],
    websiteUrl: "https://www.mercadolibre.com.ar",
    instagramUrl: "https://www.instagram.com/mercadolibre",
  },
  {
    id: "tiendli",
    name: "Tiendli",
    summary: "Plataforma de e-commerce uruguaya. Tienda online y catálogo digital.",
    originCountry: "Uruguay",
    websiteUrl: "https://tiendli.com",
    instagramUrl: "https://www.instagram.com/tiendli",
  },
  {
    id: "commercy",
    name: "Commercy",
    summary: "E-commerce argentino para PyMEs. Tienda online con integraciones locales.",
    originCountry: "Argentina",
    websiteUrl: "https://commercy.com.ar",
    instagramUrl: "https://www.instagram.com/commercy.ar",
  },
  {
    id: "wendo",
    name: "Wendo",
    summary: "Tienda online y catálogo para vender por WhatsApp e Instagram en Argentina.",
    originCountry: "Argentina",
    websiteUrl: "https://wendo.com.ar",
    instagramUrl: "https://www.instagram.com/wendo.ar",
  },
  {
    id: "lapyme",
    name: "La Pyme",
    summary: "ERP cloud para PyMEs: ventas, stock, ARCA, tesorería e integraciones e-commerce.",
    originCountry: "Argentina",
    websiteUrl: "https://www.lapyme.com.ar",
    instagramUrl: "https://www.instagram.com/lapyme.ar",
  },
  {
    id: "dragonfish-zoo-logic",
    name: "Dragonfish / Zoo Logic",
    summary: "ERP y POS omnicanal. Stock unificado entre local, e-commerce y marketplaces.",
    originCountry: "Argentina",
    websiteUrl: "https://www.zoologic.com.ar",
    instagramUrl: "https://www.instagram.com/zoologicarg",
  },
  {
    id: "tango-software",
    name: "Tango Gestión",
    summary: "ERP líder en Argentina. Gestión, contabilidad y Tango eCommerce.",
    originCountry: "Argentina",
    websiteUrl: "https://www.tango.software",
    instagramUrl: "https://www.instagram.com/tango.software",
  },
  {
    id: "pistacho",
    name: "Pistacho",
    summary: "Tienda online y catálogo digital LATAM. WhatsApp, pagos y gestión simple.",
    originCountry: "Argentina",
    extraCountries: ["Latinoamérica"],
    websiteUrl: "https://www.pistacho.app",
    instagramUrl: "https://www.instagram.com/pistacho.app",
  },
  {
    id: "wix",
    name: "Wix",
    summary: "Plataforma global de sitios web y e-commerce con editor visual.",
    originCountry: "Israel",
    websiteUrl: "https://www.wix.com",
    instagramUrl: "https://www.instagram.com/wix",
  },
  {
    id: "odoo",
    name: "Odoo",
    summary: "Suite ERP open-source modular. CRM, inventario, e-commerce y contabilidad.",
    originCountry: "Bélgica",
    websiteUrl: "https://www.odoo.com",
    instagramUrl: "https://www.instagram.com/odoo.official",
  },
  {
    id: "vtex",
    name: "VTEX",
    summary: "Plataforma enterprise de e-commerce. Marketplace, OMS y composable commerce.",
    originCountry: "Brasil",
    websiteUrl: "https://vtex.com",
    instagramUrl: "https://www.instagram.com/vtex",
  },
  {
    id: "shoperly",
    name: "Shoperly",
    summary: "E-commerce paraguayo para PyMEs. Tienda online con pagos y envíos locales.",
    originCountry: "Paraguay",
    websiteUrl: "https://www.shoperly.app",
    instagramUrl: "https://www.instagram.com/shoperly",
  },
  {
    id: "plenishop",
    name: "Plenishop",
    summary: "Plataforma peruana de tienda online. Catálogo, pagos y delivery.",
    originCountry: "Perú",
    websiteUrl: "https://plenishop.com",
    instagramUrl: "https://www.instagram.com/plenishop",
  },
  {
    id: "neolo",
    name: "Neolo",
    summary: "Hosting y e-commerce argentino. Tienda online con dominio y pagos integrados.",
    originCountry: "Argentina",
    websiteUrl: "https://www.neolo.com",
    instagramUrl: "https://www.instagram.com/neolohosting",
  },
  {
    id: "jumpseller",
    name: "Jumpseller",
    summary: "Plataforma de e-commerce chilena/portuguesa. Tienda online multicanal.",
    originCountry: "Portugal",
    websiteUrl: "https://jumpseller.com",
    instagramUrl: "https://www.instagram.com/jumpseller",
  },
  {
    id: "mitienda",
    name: "Mitienda",
    summary: "Tienda online uruguaya. Catálogo digital y ventas por WhatsApp.",
    originCountry: "Uruguay",
    websiteUrl: "https://mitienda.uy",
    instagramUrl: "https://www.instagram.com/mitienda.uy",
  },
  {
    id: "prestashop",
    name: "PrestaShop",
    summary: "Plataforma open-source de e-commerce. Altamente personalizable.",
    originCountry: "Francia",
    websiteUrl: "https://www.prestashop.com",
    instagramUrl: "https://www.instagram.com/prestashop",
  },
  {
    id: "bigcommerce",
    name: "BigCommerce",
    summary: "Plataforma SaaS de e-commerce enterprise y mid-market.",
    originCountry: "Australia",
    websiteUrl: "https://www.bigcommerce.com",
    instagramUrl: "https://www.instagram.com/bigcommerce",
  },
  {
    id: "bsale",
    name: "Bsale",
    summary: "POS y facturación electrónica chilena. Retail + e-commerce integrado.",
    originCountry: "Chile",
    websiteUrl: "https://www.bsale.cl",
    instagramUrl: "https://www.instagram.com/bsalecl",
  },
  {
    id: "fenicio",
    name: "Fenicio",
    summary: "Plataforma uruguaya de e-commerce. Tienda online y omnicanal.",
    originCountry: "Uruguay",
    websiteUrl: "https://fenicio.io",
    instagramUrl: "https://www.instagram.com/fenicio.io",
  },
  {
    id: "siigo",
    name: "Siigo",
    summary: "ERP y facturación electrónica colombiano. Contabilidad, POS y nómina.",
    originCountry: "Colombia",
    extraCountries: ["Latinoamérica"],
    websiteUrl: "https://www.siigo.com",
    instagramUrl: "https://www.instagram.com/siigo",
  },
  {
    id: "bootic",
    name: "Bootic",
    summary: "Marketplace y tienda online chilena para emprendedores.",
    originCountry: "Chile",
    websiteUrl: "https://www.bootic.com",
    instagramUrl: "https://www.instagram.com/bootic",
  },
  {
    id: "xcommerce",
    name: "XCommerce",
    summary: "Plataforma chilena de e-commerce B2B y B2C.",
    originCountry: "Chile",
    websiteUrl: "https://xcommerce.cl",
    instagramUrl: "https://www.instagram.com/xcommerce.cl",
  },
  {
    id: "take-app",
    name: "Take App",
    summary: "Catálogo y tienda para WhatsApp. Pedidos, pagos y delivery integrados.",
    originCountry: "Singapur",
    extraCountries: ["Latinoamérica", "Internacional"],
    websiteUrl: "https://take.app",
    instagramUrl: "https://www.instagram.com/takeapp",
  },
  {
    id: "alegra",
    name: "Alegra",
    summary: "Facturación electrónica y contabilidad cloud para PyMEs en LATAM.",
    originCountry: "Colombia",
    extraCountries: ["Centroamérica", "Latinoamérica"],
    websiteUrl: "https://www.alegra.com",
    instagramUrl: "https://www.instagram.com/alegra",
  },
  {
    id: "baggo",
    name: "Baggo",
    summary: "Tienda online colombiana. Catálogo, WhatsApp y pagos para emprendedores.",
    originCountry: "Colombia",
    websiteUrl: "https://baggo.co",
    instagramUrl: "https://www.instagram.com/baggo.co",
  },
  {
    id: "tiendipy",
    name: "Tiendipy",
    summary: "E-commerce colombiano para PyMEs. Tienda online y catálogo digital.",
    originCountry: "Colombia",
    websiteUrl: "https://tiendipy.com",
    instagramUrl: "https://www.instagram.com/tiendipy",
  },
  {
    id: "comerciaya",
    name: "Comerciaya",
    summary: "Plataforma colombiana de tienda online y gestión comercial.",
    originCountry: "Colombia",
    websiteUrl: "https://comerciaya.com",
    instagramUrl: "https://www.instagram.com/comerciaya",
  },
  {
    id: "webtana",
    name: "Webtana",
    summary: "Plataforma regional de e-commerce para Centroamérica y LATAM.",
    originCountry: "Guatemala",
    websiteUrl: "https://webtana.com",
    instagramUrl: "https://www.instagram.com/webtana",
  },
  {
    id: "nidux",
    name: "Nidux",
    summary: "Plataforma eCommerce + POS para Centroamérica. Marketplace Nidux Shop.",
    originCountry: "Costa Rica",
    extraCountries: ["Centroamérica"],
    websiteUrl: "https://www.nidux.com",
    instagramUrl: "https://www.instagram.com/NIDUXlatam",
  },
  {
    id: "qtiko",
    name: "Q'Tiko",
    summary: "Sistema de gestión costarricense: POS, inventario, facturación y tienda online.",
    originCountry: "Costa Rica",
    websiteUrl: "https://qtiko.com",
    instagramUrl: "https://www.instagram.com/qtiko",
    note: "Competidor local muy parecido a Mercantis en CR.",
  },
  {
    id: "blume",
    name: "Blume",
    summary: "Retail conectado: e-commerce, inventario, WhatsApp/IG y lealtad.",
    originCountry: "Costa Rica",
    extraCountries: ["Guatemala", "Nicaragua"],
    websiteUrl: "https://www.madebyblume.com",
    instagramUrl: "https://www.instagram.com/blumeapps",
  },
  {
    id: "wstorecr",
    name: "WStoreCR",
    summary: "Tienda online costarricense. Catálogo, WhatsApp y pagos locales.",
    originCountry: "Costa Rica",
    websiteUrl: "https://wstorecr.com",
    instagramUrl: "https://www.instagram.com/wstorecr",
  },
  {
    id: "towami",
    name: "Towami",
    summary: "E-commerce costarricense para PyMEs. Tienda online y delivery.",
    originCountry: "Costa Rica",
    websiteUrl: "https://towami.com",
    instagramUrl: "https://www.instagram.com/towami",
  },
  {
    id: "contifico-siigo",
    name: "Contífico / Siigo",
    summary: "ERP y facturación electrónica para Ecuador (SRI). POS y contabilidad.",
    originCountry: "Ecuador",
    websiteUrl: "https://www.siigo.com/ec",
    instagramUrl: "https://www.instagram.com/siigocontifico",
  },
  {
    id: "rocket-ec",
    name: "Rocket",
    summary: "Plataforma ecuatoriana de e-commerce y gestión para PyMEs.",
    originCountry: "Ecuador",
    websiteUrl: "https://rocket.com.ec",
    instagramUrl: "https://www.instagram.com/rocket.ec",
  },
  {
    id: "qpaypro",
    name: "Qpaypro / Qpayshop",
    summary: "Pasarela de pagos y tienda online en Centroamérica.",
    originCountry: "Guatemala",
    websiteUrl: "https://qpaypro.com",
    instagramUrl: "https://www.instagram.com/qpaypro",
  },
  {
    id: "ecolatam",
    name: "E-coLATAM",
    summary: "Plataforma regional de e-commerce para Centroamérica y LATAM.",
    originCountry: "Guatemala",
    websiteUrl: "https://www.ecolatam.com",
    instagramUrl: "https://www.instagram.com/ecolatamshop",
  },
  {
    id: "recurrente",
    name: "Recurrente",
    summary: "Tienda en línea guatemalteca. Catálogo, WhatsApp y pagos locales.",
    originCountry: "Guatemala",
    websiteUrl: "https://www.recurrente.com",
    instagramUrl: "https://www.instagram.com/recurrente",
    note: "Vigilancia inmediata — muy parecido a Mercantis.",
  },
  {
    id: "cuadra",
    name: "Cuadra",
    summary: "Sistema de gestión guatemalteco: inventario, ventas y tienda online.",
    originCountry: "Guatemala",
    websiteUrl: "https://cuadra.com.gt",
    instagramUrl: "https://www.instagram.com/cuadra.gt",
  },
  {
    id: "vexo-os",
    name: "Vexo OS",
    summary: "Sistema operativo de gestión hondureño para retail y PyMEs.",
    originCountry: "Honduras",
    websiteUrl: "https://www.vexoos.com",
    instagramUrl: "https://www.instagram.com/vexoos",
  },
  {
    id: "bind-erp",
    name: "Bind ERP",
    summary: "ERP mexicano cloud. Inventario, facturación y e-commerce.",
    originCountry: "México",
    websiteUrl: "https://bind.com.mx",
    instagramUrl: "https://www.instagram.com/bindmx",
  },
  {
    id: "kioskito",
    name: "Kioskito",
    summary: "App panameña de tienda online y catálogo para WhatsApp.",
    originCountry: "Panamá",
    websiteUrl: "https://kioskito.app",
    instagramUrl: "https://www.instagram.com/kioskito.app",
  },
  {
    id: "tiendy",
    name: "Tiendy",
    summary: "Tienda online paraguaya: WhatsApp, variantes, IA, empleados y 0% comisión.",
    originCountry: "Paraguay",
    websiteUrl: "https://www.tiendy.com.py",
    instagramUrl: "https://www.instagram.com/tiendy.com.py",
    note: "Especialmente parecido a Mercantis. Vigilancia inmediata.",
  },
  {
    id: "digital-shop-py",
    name: "Digital Shop PY",
    summary: "E-commerce paraguayo para PyMEs. Tienda online y catálogo digital.",
    originCountry: "Paraguay",
    websiteUrl: "https://digitalshop.com.py",
    instagramUrl: "https://www.instagram.com/digitalshop.py",
  },
  {
    id: "agilpedido",
    name: "AgilPedido",
    summary: "Catálogo y pedidos por WhatsApp para comercios en LATAM.",
    originCountry: "Argentina",
    websiteUrl: "https://agilpedido.com",
    instagramUrl: "https://www.instagram.com/agilpedido",
  },
  {
    id: "negocia-pe",
    name: "Negocia.pe",
    summary: "Tienda online peruana. Catálogo, WhatsApp y gestión para PyMEs.",
    originCountry: "Perú",
    websiteUrl: "https://www.negocia.pe",
    instagramUrl: "https://www.instagram.com/negocia.pe",
  },
  {
    id: "catalog-pe",
    name: "Catalog.pe",
    summary: "Catálogo digital peruano para vender por WhatsApp e Instagram.",
    originCountry: "Perú",
    websiteUrl: "https://catalog.pe",
    instagramUrl: "https://www.instagram.com/catalog.pe",
  },
  {
    id: "rocketfy",
    name: "Rocketfy",
    summary: "Ecosistema e-commerce colombiano: tienda, logística, pagos y comunidad.",
    originCountry: "Colombia",
    extraCountries: ["México", "Perú", "Brasil"],
    websiteUrl: "https://www.rocketfy.com",
    instagramUrl: "https://www.instagram.com/rocketfy.co",
    tiktokUrl: "https://www.tiktok.com/@rocketfy.co",
  },
  {
    id: "defontana",
    name: "Defontana",
    summary: "ERP 100% web con IA para PyMEs. Integra e-commerce y marketplaces.",
    originCountry: "Chile",
    extraCountries: ["Perú", "Colombia", "México"],
    websiteUrl: "https://www.defontana.com",
    instagramUrl: "https://www.instagram.com/defontana",
  },
  {
    id: "ucinema",
    name: "uCinema",
    summary: "Plataforma puertorriqueña de e-commerce y contenido digital.",
    originCountry: "Puerto Rico",
    websiteUrl: "https://ucinema.com",
    instagramUrl: "https://www.instagram.com/ucinema.pr",
  },
  {
    id: "wishopai",
    name: "Wishopai",
    summary: "Tienda online con IA para emprendedores en LATAM y Caribe.",
    originCountry: "Internacional",
    websiteUrl: "https://wishopai.com",
    instagramUrl: "https://www.instagram.com/wishopai",
  },
  {
    id: "square-online",
    name: "Square Online",
    summary: "Tienda online de Square. Integrada con POS y pagos.",
    originCountry: "Estados Unidos",
    websiteUrl: "https://squareup.com/us/en/online-store",
    instagramUrl: "https://www.instagram.com/square",
  },
  {
    id: "ecwid",
    name: "Ecwid / Lightspeed",
    summary: "Widget de e-commerce embebible. Tienda en cualquier sitio web.",
    originCountry: "Canadá",
    websiteUrl: "https://www.ecwid.com",
    instagramUrl: "https://www.instagram.com/ecwid",
  },
  {
    id: "squarespace",
    name: "Squarespace",
    summary: "Plataforma global de sitios web y e-commerce con diseño premium.",
    originCountry: "Estados Unidos",
    websiteUrl: "https://www.squarespace.com",
    instagramUrl: "https://www.instagram.com/squarespace",
  },
  {
    id: "clover",
    name: "Clover",
    summary: "POS y e-commerce de Fiserv para retail y restaurantes.",
    originCountry: "Estados Unidos",
    websiteUrl: "https://www.clover.com",
    instagramUrl: "https://www.instagram.com/clover",
  },
  {
    id: "magento",
    name: "Adobe Commerce / Magento",
    summary: "Plataforma enterprise de e-commerce de Adobe. Altamente personalizable.",
    originCountry: "Estados Unidos",
    websiteUrl: "https://business.adobe.com/products/magento/magento-commerce.html",
    instagramUrl: "https://www.instagram.com/adobe",
  },
  {
    id: "godaddy-store",
    name: "GoDaddy Online Store",
    summary: "Tienda online de GoDaddy integrada con hosting y dominios.",
    originCountry: "Estados Unidos",
    websiteUrl: "https://www.godaddy.com/websites/online-store",
    instagramUrl: "https://www.instagram.com/godaddy",
  },
  {
    id: "vendabo",
    name: "Vendabo",
    summary: "Plataforma dominicana de tienda online y catálogo digital.",
    originCountry: "República Dominicana",
    websiteUrl: "https://vendabo.com",
    instagramUrl: "https://www.instagram.com/vendabo",
  },
  {
    id: "digimart",
    name: "Digimart",
    summary: "Tienda en línea dominicana. Catálogo, WhatsApp y pagos locales.",
    originCountry: "República Dominicana",
    websiteUrl: "https://www.digimart.cloud",
    instagramUrl: "https://www.instagram.com/digimart.cloud",
  },
  {
    id: "tiendu",
    name: "Tiendu",
    summary: "Tienda online uruguaya. Catálogo digital y ventas por WhatsApp.",
    originCountry: "Uruguay",
    websiteUrl: "https://tiendu.uy",
    instagramUrl: "https://www.instagram.com/tiendu.uy",
  },
  {
    id: "smart-business-uy",
    name: "Smart Business",
    summary: "Software de gestión uruguayo para comercios y PyMEs.",
    originCountry: "Uruguay",
    websiteUrl: "https://smartbusiness.uy",
    instagramUrl: "https://www.instagram.com/smartbusiness.uy",
  },
];

const baseCatalog: CompetitorInspiration[] = SEEDS.map((seed) => {
  const { extraCountries: _extra, ...rest } = seed;
  return {
    ...rest,
    operatingCountries: buildOperatingCountries(seed),
  };
});

const baseIds = new Set(baseCatalog.map((item) => item.id));

export const competitorCatalog: CompetitorInspiration[] = [
  ...baseCatalog,
  ...extendedCompetitorCatalog.filter((item) => !baseIds.has(item.id)),
];
