import type { CompetitorInspiration } from "@/content/competitor-inspirations";
import { getCompetitorMercantisMarkets } from "@/content/competitor-rankings";

type CompetitorSeed = Omit<CompetitorInspiration, "operatingCountries">;

function build(seed: CompetitorSeed): CompetitorInspiration {
  return {
    ...seed,
    operatingCountries: [...getCompetitorMercantisMarkets(seed.id)],
  };
}

/** Competidores del ranking global (sep 2026) — metadata verificada. */
export const EXTENDED_COMPETITOR_SEEDS: CompetitorSeed[] = [
  {
    id: "loyverse",
    name: "Loyverse",
    summary: "POS cloud gratuito para retail y gastronomía. Inventario y reportes.",
    originCountry: "Estados Unidos",
    websiteUrl: "https://loyverse.com",
    instagramUrl: "https://www.instagram.com/loyversepos",
  },
  {
    id: "bold",
    name: "Bold",
    summary: "Pagos, datáfonos y soluciones financieras para comercios en Colombia.",
    originCountry: "Colombia",
    websiteUrl: "https://bold.co",
    instagramUrl: "https://www.instagram.com/somosbold.co",
  },
  {
    id: "sicar",
    name: "SICAR",
    summary: "Sistema de punto de venta mexicano para comercios y retail.",
    originCountry: "México",
    websiteUrl: "https://www.sicar.mx",
    instagramUrl: "https://www.instagram.com/sicarpv",
  },
  {
    id: "kyte",
    name: "Kyte",
    summary: "Catálogo digital, inventario y pedidos por WhatsApp. POS móvil para PyMEs.",
    originCountry: "Brasil",
    websiteUrl: "https://www.kyteapp.com",
    instagramUrl: "https://www.instagram.com/kyte.app",
  },
  {
    id: "fudo",
    name: "Fudo",
    summary: "Software de gestión para restaurantes en LATAM. POS, delivery y stock.",
    originCountry: "Argentina",
    websiteUrl: "https://fu.do",
    instagramUrl: "https://www.instagram.com/socialfudo",
  },
  {
    id: "sap-business-one",
    name: "SAP Business One",
    summary: "ERP enterprise para PyMEs en crecimiento. Finanzas, inventario y CRM.",
    originCountry: "Alemania",
    websiteUrl: "https://www.sap.com/products/erp/business-one.html",
    instagramUrl: "https://www.instagram.com/sap",
  },
  {
    id: "oracle-netsuite",
    name: "Oracle NetSuite",
    summary: "ERP cloud enterprise. Finanzas, e-commerce y gestión unificada.",
    originCountry: "Estados Unidos",
    websiteUrl: "https://www.netsuite.com",
    instagramUrl: "https://www.instagram.com/netsuite",
  },
  {
    id: "aspel",
    name: "Aspel CAJA / ADM",
    summary: "Sistemas de punto de venta y administración para PyMEs mexicanas (Siigo Aspel).",
    originCountry: "México",
    websiteUrl: "https://www.aspel.com.mx",
    instagramUrl: "https://www.instagram.com/siigoaspel",
  },
  {
    id: "tienda-negocio",
    name: "Tienda Negocio",
    summary: "Catálogo y tienda para WhatsApp. Gestión simple para comercios.",
    originCountry: "Argentina",
    websiteUrl: "https://tiendanegocio.com",
    instagramUrl: "https://www.instagram.com/tienda.negocio",
  },
  {
    id: "xubio",
    name: "Xubio",
    summary: "Contabilidad y facturación cloud para PyMEs argentinas.",
    originCountry: "Argentina",
    websiteUrl: "https://xubio.com",
    instagramUrl: "https://www.instagram.com/xubiogestion",
  },
  {
    id: "vendty",
    name: "Vendty",
    summary: "POS y tienda online integrada. Catálogo, WhatsApp y pagos en LATAM.",
    originCountry: "Colombia",
    websiteUrl: "https://www.vendty.com",
    instagramUrl: "https://www.instagram.com/vendtyapps",
  },
  {
    id: "toteat",
    name: "Toteat",
    summary: "Software de gestión para restaurantes en Chile y LATAM.",
    originCountry: "Chile",
    websiteUrl: "https://toteat.com",
    instagramUrl: "https://www.instagram.com/toteat_software",
  },
  {
    id: "colppy",
    name: "Colppy",
    summary: "Contabilidad online para PyMEs argentinas. Facturación e inventario.",
    originCountry: "Argentina",
    websiteUrl: "https://colppy.com",
    instagramUrl: "https://www.instagram.com/colppy_com",
  },
  {
    id: "eleventa",
    name: "eleventa",
    summary: "Punto de venta mexicano para abarrotes y retail. Inventario y facturación CFDI.",
    originCountry: "México",
    websiteUrl: "https://www.eleventa.com",
    instagramUrl: "https://www.instagram.com/eleventaoficial",
  },
  {
    id: "cobrando-app",
    name: "Cobrando.app",
    summary: "Sistema POS online para comercios argentinos. Ventas, stock y cuentas corrientes.",
    originCountry: "Argentina",
    websiteUrl: "https://cobrando.app",
    instagramUrl: "https://www.instagram.com/cobrando.app",
    note: "Desarrollado en Buenos Aires. No confundir con Audens Food (España).",
  },
  {
    id: "contabilium",
    name: "Contabilium",
    summary: "Gestión contable y facturación para PyMEs en Argentina y LATAM.",
    originCountry: "Argentina",
    websiteUrl: "https://contabilium.com",
    instagramUrl: "https://www.instagram.com/contabilium",
  },
  {
    id: "loggro",
    name: "Loggro",
    summary: "ERP cloud colombiano. Contabilidad, nómina y facturación.",
    originCountry: "Colombia",
    websiteUrl: "https://loggro.com",
    instagramUrl: "https://www.instagram.com/tuloggro",
  },
  {
    id: "maxirest",
    name: "Maxirest",
    summary: "Software líder para gastronomía en Argentina. POS, delivery y stock.",
    originCountry: "Argentina",
    websiteUrl: "https://www.maxirest.com",
    instagramUrl: "https://www.instagram.com/maxirest.oficial",
  },
  {
    id: "venddy",
    name: "Venddy",
    summary: "Tienda online + POS con inventario unificado. WhatsApp, Wompi y Nequi.",
    originCountry: "Colombia",
    websiteUrl: "https://venddy.co",
    instagramUrl: "https://www.instagram.com/venddy.co",
  },
  {
    id: "key",
    name: "Key",
    summary: "ERP y facturación electrónica para PyMEs en Perú.",
    originCountry: "Perú",
    websiteUrl: "https://keyfacil.com",
    instagramUrl: "https://www.instagram.com/keyfacil",
  },
  {
    id: "niabit",
    name: "Niabit",
    summary: "Tiendas online y pedidos por WhatsApp para emprendedores argentinos.",
    originCountry: "Argentina",
    websiteUrl: "https://www.niabit.com.ar",
    instagramUrl: "https://www.instagram.com/niabit_online",
  },
  {
    id: "cataly",
    name: "Cataly",
    summary: "Tienda online y catálogo digital para emprendedores en LATAM.",
    originCountry: "Colombia",
    websiteUrl: "https://cataly.io",
    instagramUrl: "https://www.instagram.com/cataly.io",
  },
  {
    id: "minitienda",
    name: "Minitienda",
    summary: "Catálogo digital para WhatsApp. Gestión simple de productos y pedidos.",
    originCountry: "Colombia",
    websiteUrl: "https://minitienda.co",
    instagramUrl: "https://www.instagram.com/minitienda.co",
  },
  {
    id: "pedido-simple",
    name: "PedidoSimple",
    summary: "Menú digital y pedidos por WhatsApp para restaurantes y comercios.",
    originCountry: "Argentina",
    websiteUrl: "https://www.pedidosimple.com.ar",
    instagramUrl: "https://www.instagram.com/pedidosimple.ar",
  },
  {
    id: "mitienda24",
    name: "MiTienda24",
    summary: "Tienda online y catálogo digital para emprendedores LATAM.",
    originCountry: "Colombia",
    websiteUrl: "https://mitienda.la",
    instagramUrl: "https://www.instagram.com/mitienda.la",
  },
  {
    id: "mercadily",
    name: "Mercadily",
    summary: "Catálogo y tienda para vender por redes sociales y WhatsApp.",
    originCountry: "Colombia",
    websiteUrl: "https://mercadily.com",
    instagramUrl: "https://www.instagram.com/mercadily",
  },
  {
    id: "agencyrime",
    name: "AgencyRime",
    summary: "Agencia y plataforma de tienda online para emprendedores digitales.",
    originCountry: "Colombia",
    websiteUrl: "https://agencyrime.com",
    instagramUrl: "https://www.instagram.com/agencyrime",
  },
  {
    id: "micatalogo-uno",
    name: "MiCatalogo.uno",
    summary: "Catálogo digital gratuito para WhatsApp e Instagram.",
    originCountry: "Argentina",
    websiteUrl: "https://micatalogo.uno",
    instagramUrl: "https://www.instagram.com/micatalogo.uno",
  },
];

export const extendedCompetitorCatalog: CompetitorInspiration[] =
  EXTENDED_COMPETITOR_SEEDS.map(build);
