import { inspirationMedia } from "@/content/inspiration-media";
import type { InspirationLinkItem } from "@/content/inspiration-links";

export const creativeInspirations: InspirationLinkItem[] = [
  {
    id: "ig-dcj8g7vp-qu",
    platform: "Instagram",
    url: "https://www.instagram.com/p/Dcj8G7VP-QU/",
    title: "Referencia Instagram",
    media: inspirationMedia["ig-dcj8g7vp-qu"],
    note: "Guardado desde inspiración creativa. Estética y composición para adaptar.",
  },
  {
    id: "ig-dcpd25upfie",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DcpD25uPFie/",
    title: "Referencia Instagram",
    media: inspirationMedia["ig-dcpd25upfie"],
    note: "Guardado desde inspiración creativa. Estética y composición para adaptar.",
  },
  {
    id: "ig-dcwytdmvkx-",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DcwytdmvKx-/",
    title: "Referencia Instagram",
    media: inspirationMedia["ig-dcwytdmvkx-"],
    note: "Guardado desde inspiración creativa. Estética y composición para adaptar.",
  },
  {
    id: "ig-db8bylkx3ch",
    platform: "Instagram",
    url: "https://www.instagram.com/p/Db8bylKx3Ch/",
    title: "Referencia Instagram",
    media: inspirationMedia["ig-db8bylkx3ch"],
    note: "Guardado desde inspiración creativa. Estética y composición para adaptar.",
  },
  {
    id: "ig-dcpduyiolwf",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DcPDUYioLWf/",
    title: "Referencia Instagram",
    media: inspirationMedia["ig-dcpduyiolwf"],
    note: "Guardado desde inspiración creativa. Estética y composición para adaptar.",
  },
  {
    id: "ig-db9kcmoxyxt",
    platform: "Instagram",
    url: "https://www.instagram.com/p/Db9KcMoxyXT/",
    title: "Referencia Instagram",
    media: inspirationMedia["ig-db9kcmoxyxt"],
    note: "Guardado desde inspiración creativa. Estética y composición para adaptar.",
  },
  {
    id: "ig-dcbs_oqr8pn",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DcBs_OqR8PN/",
    title: "Referencia Instagram",
    media: inspirationMedia["ig-dcbs_oqr8pn"],
    note: "Guardado desde inspiración creativa. Estética y composición para adaptar.",
  },
  {
    id: "ig-dcesthwx39c",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DcEStHwx39c/",
    title: "Referencia Instagram",
    media: inspirationMedia["ig-dcesthwx39c"],
    note: "Guardado desde inspiración creativa. Estética y composición para adaptar.",
  },
  {
    id: "ig-dce4cjuxs1x",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DcE4CjUxs1x/",
    title: "Referencia Instagram",
    media: inspirationMedia["ig-dce4cjuxs1x"],
    note: "Guardado desde inspiración creativa. Estética y composición para adaptar.",
  },
  {
    id: "ig-dcmnhl_krp-",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DcMnHL_kRp-/",
    title: "Referencia Instagram",
    media: inspirationMedia["ig-dcmnhl_krp-"],
    note: "Guardado desde inspiración creativa. Estética y composición para adaptar.",
  },
  {
    id: "ig-dcj10ujayma",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DcJ10uJAYMa/",
    title: "Referencia Instagram",
    media: inspirationMedia["ig-dcj10ujayma"],
    note: "Guardado desde inspiración creativa. Estética y composición para adaptar.",
  },
  {
    id: "ig-dcoe4ycxtdi",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DcOe4ycxTdI/",
    title: "Referencia Instagram",
    media: inspirationMedia["ig-dcoe4ycxtdi"],
    note: "Guardado desde inspiración creativa. Estética y composición para adaptar.",
  },
  {
    id: "ig-dcmoecirhzg",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DcMOEciRhzg/",
    title: "Referencia Instagram",
    media: inspirationMedia["ig-dcmoecirhzg"],
    note: "Guardado desde inspiración creativa. Estética y composición para adaptar.",
  },
  {
    id: "ig-dcq_c7qxq75",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DcQ_C7QxQ75/",
    title: "Referencia Instagram",
    media: inspirationMedia["ig-dcq_c7qxq75"],
    note: "Guardado desde inspiración creativa. Estética y composición para adaptar.",
  },
  {
    id: "ig-dcufhvmom3e",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DcUFhVMoM3E/",
    title: "Referencia Instagram",
    media: inspirationMedia["ig-dcufhvmom3e"],
    note: "Guardado desde inspiración creativa. Estética y composición para adaptar.",
  },
  {
    id: "ig-dcw3lxnavko",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DcW3LxNAVko/",
    title: "Referencia Instagram",
    media: inspirationMedia["ig-dcw3lxnavko"],
    note: "Guardado desde inspiración creativa. Estética y composición para adaptar.",
  },
  {
    id: "ig-dcbfiz2rzwy",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DcbfiZ2RZwY/",
    title: "Referencia Instagram",
    media: inspirationMedia["ig-dcbfiz2rzwy"],
    note: "Guardado desde inspiración creativa. Estética y composición para adaptar.",
  },
  {
    id: "ig-dcb7nuca9mf",
    platform: "Instagram",
    url: "https://www.instagram.com/p/Dcb7nUCA9mf/",
    title: "Referencia Instagram",
    media: inspirationMedia["ig-dcb7nuca9mf"],
    note: "Guardado desde inspiración creativa. Estética y composición para adaptar.",
  },
  {
    id: "ig-dcecov5inhx",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DcecOV5INhx/",
    title: "Referencia Instagram",
    media: inspirationMedia["ig-dcecov5inhx"],
    note: "Guardado desde inspiración creativa. Estética y composición para adaptar.",
  },
  {
    id: "ig-dcejzjjrkgt",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DceJzjjRKgT/",
    title: "Referencia Instagram",
    media: inspirationMedia["ig-dcejzjjrkgt"],
    note: "Guardado desde inspiración creativa. Estética y composición para adaptar.",
  },
  {
    id: "ig-dcg3dgsa0ka",
    platform: "Instagram",
    url: "https://www.instagram.com/p/Dcg3dGsA0ka/",
    title: "Referencia Instagram",
    media: inspirationMedia["ig-dcg3dgsa0ka"],
    note: "Guardado desde inspiración creativa. Estética y composición para adaptar.",
  },
  {
    id: "ig-dci_qvhx6by",
    platform: "Instagram",
    url: "https://www.instagram.com/p/Dci_qVHx6by/",
    title: "Referencia Instagram",
    media: inspirationMedia["ig-dci_qvhx6by"],
    note: "Guardado desde inspiración creativa. Estética y composición para adaptar.",
  },
  {
    id: "ig-dczkqswofww",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DczKqsWoFWW/",
    title: "Referencia Instagram",
    media: inspirationMedia["ig-dczkqswofww"],
    note: "Guardado desde inspiración creativa. Estética y composición para adaptar.",
  },
  {
    id: "ig-ddcycjsdlb0",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DdCyCjsDlB0/",
    title: "Referencia Instagram",
    media: inspirationMedia["ig-ddcycjsdlb0"],
    note: "Guardado desde inspiración creativa. Estética y composición para adaptar.",
  },
  {
    id: "ig-ddj5oixkyuv",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DdJ5oIXkYuv/",
    title: "Referencia Instagram",
    media: inspirationMedia["ig-ddj5oixkyuv"],
    note: "Guardado desde inspiración creativa. Estética y composición para adaptar.",
  },
  {
    id: "ig-dud30aakumo",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DUd30AakUMo/",
    title: "Referencia Instagram",
    media: inspirationMedia["ig-dud30aakumo"],
    note: "Guardado desde inspiración creativa. Estética y composición para adaptar.",
  },
  {
    id: "ig-dvb-2kokvad",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DVB-2KokVAd/",
    title: "Referencia Instagram",
    media: inspirationMedia["ig-dvb-2kokvad"],
    note: "Guardado desde inspiración creativa. Estética y composición para adaptar.",
  },
  {
    id: "ig-dcwttgupxoc",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DcwtTgUPxoc/",
    title: "Referencia Instagram",
    media: inspirationMedia["ig-dcwttgupxoc"],
    note: "Formato y ritmo visual para inspirar un creativo de Mercantis.",
  },
  {
    id: "cosmos-468606743",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/468606743",
    title: "From the &#x27;Le Lendemain&#x27; editorial for Numéro Netherlands, photograp...",
    media: inspirationMedia["cosmos-468606743"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-635809099",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/635809099",
    title: "AI-generated cinematic portrait created using Midjourney.",
    media: inspirationMedia["cosmos-635809099"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1884704268",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1884704268",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-1884704268"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-539173763",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/539173763",
    title: "Alt-pop artist Artemas photographed by David Reiss for an editorial.",
    media: inspirationMedia["cosmos-539173763"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-139958314",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/139958314",
    title: "An editorial portrait by photographer Jai Mayhew.",
    media: inspirationMedia["cosmos-139958314"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1121133607",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1121133607",
    title: "An AI-generated image from the series Editorial Images.",
    media: inspirationMedia["cosmos-1121133607"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1234232371",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1234232371",
    title: "Skincare editorial for GLAMOUR Magazine SA. Photo by Sebastian Hilg...",
    media: inspirationMedia["cosmos-1234232371"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-473451274",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/473451274",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-473451274"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1709428031",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1709428031",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-1709428031"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1668928375",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1668928375",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-1668928375"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-112523357",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/112523357",
    title: "Alarm app UI concept by Nina Skrbic. Mockup by Akoya Mockups.",
    media: inspirationMedia["cosmos-112523357"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1848185825",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1848185825",
    title: "The LB26 W02 Le iPhone 01 Mockup by Bendito Mockup displays a websi...",
    media: inspirationMedia["cosmos-1848185825"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-2023404280",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/2023404280",
    title: "Photograph by Lucho Rangel for Nina Ricci.",
    media: inspirationMedia["cosmos-2023404280"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-40030964",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/40030964",
    title: "Website for photographer David William Baum, developed by Tim Rouss...",
    media: inspirationMedia["cosmos-40030964"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-937211480",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/937211480",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-937211480"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-148393594",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/148393594",
    title: "UI/UX design for A Social Polling App by Kaiya McCormick, shown on...",
    media: inspirationMedia["cosmos-148393594"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1638632371",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1638632371",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-1638632371"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1234583745",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1234583745",
    title: "Art by ily frills.",
    media: inspirationMedia["cosmos-1234583745"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-715162508",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/715162508",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-715162508"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1377636874",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1377636874",
    title: "A 2014 photo of Andre 3000 at Wax &#x27;n&#x27; Facts in Atlanta. Photo by Za...",
    media: inspirationMedia["cosmos-1377636874"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1065336523",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1065336523",
    title: "EXP 1, a UI/UX concept by Hard Rock Digital.",
    media: inspirationMedia["cosmos-1065336523"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1563430072",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1563430072",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-1563430072"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1399701218",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1399701218",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-1399701218"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1310422506",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1310422506",
    title: "A photorealistic AI-generated portrait with a cinematic motion blur...",
    media: inspirationMedia["cosmos-1310422506"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-2121365483",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/2121365483",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-2121365483"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-538544702",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/538544702",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-538544702"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-138864278",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/138864278",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-138864278"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1321191480",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1321191480",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-1321191480"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-380998108",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/380998108",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-380998108"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-521683759",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/521683759",
    title: "Model Elisey Bendas photographed for a workshop in Moscow.",
    media: inspirationMedia["cosmos-521683759"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-333678845",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/333678845",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-333678845"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1306510871",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1306510871",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-1306510871"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1970369498",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1970369498",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-1970369498"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-905228549",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/905228549",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-905228549"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1086876432",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1086876432",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-1086876432"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-649852734",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/649852734",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-649852734"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1280131264",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1280131264",
    title: "Photo by cottonbro studio.",
    media: inspirationMedia["cosmos-1280131264"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1611342133",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1611342133",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-1611342133"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1080022158",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1080022158",
    title: "The website for private AI company Inkwell, designed and developed...",
    media: inspirationMedia["cosmos-1080022158"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1679610769",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1679610769",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-1679610769"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-802363835",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/802363835",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-802363835"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1823997685",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1823997685",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-1823997685"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-542863554",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/542863554",
    title: "The Auro app user interface, designed by New Apology for Brite Nites.",
    media: inspirationMedia["cosmos-542863554"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1300296381",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1300296381",
    title: "Sonori, a cinematic Framer template designed by Satto.",
    media: inspirationMedia["cosmos-1300296381"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1130172207",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1130172207",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-1130172207"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1167113042",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1167113042",
    title: "A mockup of a Linktree page for Nikole Brake, founder of Shape Shif...",
    media: inspirationMedia["cosmos-1167113042"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-2116749259",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/2116749259",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-2116749259"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-996150888",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/996150888",
    title: "A portrait created using an Amaran Spotlight SE.",
    media: inspirationMedia["cosmos-996150888"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-449186270",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/449186270",
    title: "Photograph for the Bose brand identity refresh by COLLINS. Photo by...",
    media: inspirationMedia["cosmos-449186270"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1191947644",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1191947644",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-1191947644"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-934842341",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/934842341",
    title: "Model Tyg Davison wears the Patchwork Denim Bowhill Shirt by TWP. P...",
    media: inspirationMedia["cosmos-934842341"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1654649767",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1654649767",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-1654649767"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1785661624",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1785661624",
    title: "Actor Matthew McConaughey photographed by Zoey Grossman for Cigar A...",
    media: inspirationMedia["cosmos-1785661624"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-350769188",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/350769188",
    title: "A portrait of film director Christopher Nolan.",
    media: inspirationMedia["cosmos-350769188"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1027765869",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1027765869",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-1027765869"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1428268512",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1428268512",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-1428268512"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-778307600",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/778307600",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-778307600"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1589212776",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1589212776",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-1589212776"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1984986117",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1984986117",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-1984986117"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1891691644",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1891691644",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-1891691644"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-258325435",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/258325435",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-258325435"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-544604986",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/544604986",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-544604986"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1141410426",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1141410426",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-1141410426"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1662741460",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1662741460",
    title: "Artist mighty_earthling photographed by T E K for the project OUTER...",
    media: inspirationMedia["cosmos-1662741460"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-911692947",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/911692947",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-911692947"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-339701824",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/339701824",
    title: "Musician Willie J Healey. Photo by Hollie Fernando.",
    media: inspirationMedia["cosmos-339701824"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1879556332",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1879556332",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-1879556332"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1760748840",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1760748840",
    title: "A cinematic AI portrait with a surreal, soft-focus aesthetic.",
    media: inspirationMedia["cosmos-1760748840"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-949180646",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/949180646",
    title: "AI-generated artwork from the Cinematic Prompt Guide by Curious Ref...",
    media: inspirationMedia["cosmos-949180646"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-563413372",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/563413372",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-563413372"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1518508649",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1518508649",
    title: "Cinematic Prompt Share, an AI-generated portrait by Curious Refuge...",
    media: inspirationMedia["cosmos-1518508649"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-336412916",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/336412916",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-336412916"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1081097311",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1081097311",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-1081097311"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-126557623",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/126557623",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-126557623"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1556943625",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1556943625",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-1556943625"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-731587180",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/731587180",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-731587180"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1612681327",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1612681327",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-1612681327"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-176441991",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/176441991",
    title: "Portrait of David Lynch. Photo by Joe Pugliese.",
    media: inspirationMedia["cosmos-176441991"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-50363490",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/50363490",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-50363490"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1710643926",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1710643926",
    title: "Runner Justin Sorensen for Chance Running. Photo by Runners Mood.",
    media: inspirationMedia["cosmos-1710643926"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-2085160592",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/2085160592",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-2085160592"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-291937275",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/291937275",
    title: "A portrait of actor Michael Fassbender.",
    media: inspirationMedia["cosmos-291937275"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-877979813",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/877979813",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-877979813"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-748439281",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/748439281",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-748439281"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-703900168",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/703900168",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-703900168"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-882821669",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/882821669",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-882821669"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1876954706",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1876954706",
    title: "Poster for the concept brand Persona. Image by SERIFA, inspired by...",
    media: inspirationMedia["cosmos-1876954706"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1603990431",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1603990431",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-1603990431"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1598436212",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1598436212",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-1598436212"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-303565813",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/303565813",
    title: "Found on Cosmos",
    media: inspirationMedia["cosmos-303565813"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "cosmos-1486595501",
    platform: "Cosmos",
    url: "https://www.cosmos.so/e/1486595501",
    title: "Blurred feelings. Photo by Brandon Woelfel.",
    media: inspirationMedia["cosmos-1486595501"],
    note: "Referencia visual de Cosmos. Estética, composición y mood para adaptar en creativos Mercantis.",
  },
  {
    id: "x-2091477370872168895",
    platform: "X",
    url: "https://x.com/JayBorda/status/2091477370872168895",
    title: "Stop using boring typefaces, please.",
    postText: "Stop using boring typefaces, please.",
    author: "@JayBorda",
    media: inspirationMedia["x-2091477370872168895"],
    note: "@JayBorda. Carrusel de tipografías con mockups arquitectónicos. Referencia visual de pairing y jerarquía.",
  },
  {
    id: "x-2093694501919318131",
    platform: "X",
    url: "https://x.com/andriidesign1/status/2093694501919318131",
    title: "Fuentes premium gratis para tu próximo proyecto",
    postText: "Some premium free fonts I've been enjoying lately.\nSave it for your next project.",
    author: "Andrii @andriidesign1",
    media: inspirationMedia["x-2093694501919318131"],
    note: "@andriidesign1. Lista visual de fuentes con preview. Formato guardable + recurso de diseño.",
  },
  {
    id: "x-2093885794008318287",
    platform: "X",
    url: "https://x.com/omom398/status/2093885794008318287",
    title: "Prompt viral — foto a diorama arquitectónico 3D",
    postText: "このプロンプト楽しい",
    author: "YutaTanaka @omom398",
    media: inspirationMedia["x-2093885794008318287"],
    note: "@omom398. Thread de prompt IA (diorama miniatura). Referencia de efecto visual + formato hilo en X.",
  },
  {
    id: "ig-c2cqzjsrkwm",
    platform: "Instagram",
    url: "https://www.instagram.com/p/C2CQZjsrKWM/",
    title: "Branding SaaS/Web3 — monograma y sistema visual",
    media: inspirationMedia["ig-c2cqzjsrkwm"],
    note: "@sumon_yousuf. Carrusel de identidad de marca (logo, gradientes, aplicaciones). Referencia de estética B2B tech.",
  },
  {
    id: "ig-c2pzv4jypno",
    platform: "Instagram",
    url: "https://www.instagram.com/p/C2pzv4JypNo/",
    title: "UI mobile Konnect ISP — app de datos y uso",
    media: inspirationMedia["ig-c2pzv4jypno"],
    note: "@inthi.khab. Carrusel UI/UX: dashboard, métricas y paleta teal. Referencia de diseño de app.",
  },
  {
    id: "x-2096956445959082244",
    platform: "X",
    url: "https://x.com/hussain_mu20778/status/2096956445959082244?s=12",
    title: "Recent hero section designs 📌",
    postText: "Recent hero section designs 📌\n\nPick your favorite?",
    author: "Muddasir @hussain_mu20778",
    media: inspirationMedia["x-2096956445959082244"],
    note: "Guardado desde X. Texto del post + imágenes descargadas en local.",
  },
  {
    id: "ig-dbnqaqtk9hs",
    platform: "Instagram",
    url: "https://www.instagram.com/p/Dbnqaqtk9hS/",
    title: "Carrusel Instagram — referencia creativa",
    media: inspirationMedia["ig-dbnqaqtk9hs"],
    note: "Guardado desde inspiración creativa. Estética y composición para adaptar.",
  },
  {
    id: "ig-dbuousbhpjhj",
    platform: "Instagram",
    url: "https://www.instagram.com/reels/DbUOUBHPjhj/",
    title: "Reel Instagram — referencia creativa",
    media: inspirationMedia["ig-dbuousbhpjhj"],
    note: "Formato y ritmo visual para inspirar un creativo de Mercantis.",
  },
];
