import type { InspirationMediaSlide } from "@/content/inspiration-links";
import { inspirationMedia } from "@/content/inspiration-media";

export type OrganicPlatform = "TikTok" | "Instagram" | "YouTube" | "X";

export type OrganicPostInspiration = {
  id: string;
  kind: "post";
  platform: OrganicPlatform;
  url: string;
  title: string;
  previewImage?: string;
  media?: InspirationMediaSlide[];
  postText?: string;
  author?: string;
  note?: string;
  formatIds?: string[];
};

export type OrganicCommentInspiration = {
  id: string;
  kind: "comment";
  platform: OrganicPlatform;
  text: string;
  postUrl: string;
};

export type OrganicInspiration = OrganicPostInspiration | OrganicCommentInspiration;

export const organicInspirations: OrganicInspiration[] = [
  {
    id: "x-2087622514172142030",
    kind: "post",
    platform: "X",
    url: "https://x.com/chorch_md/status/2087622514172142030",
    title: "Loops Workflow API vs Resend para emails con agentes",
    postText:
      "Todos hablan de Resend cuando quieren conectar agentes con una API para enviar emails, pero la verdad es que @loops no se queda atrás lanzando cositas y compiten el segmento de usuarios.\n\nAhora presentaron Workflow API que permite que vos le digas en lenguaje natural a tus agentes que construyan un flujo de emails automatizado para mejorar la activación de usuarios, o para reconectar con usuarios que hayan abandonado hace X meses, o lo que se te ocurra.",
    author: "Chorch @chorch_md",
    note: "@chorch_md. Intel SaaS: flujos de email en lenguaje natural para activación y reengagement.",
  },
  {
    id: "tt-7509148365083397382",
    kind: "post",
    platform: "TikTok",
    url: "https://www.tiktok.com/@studywzue/photo/7509148365083397382",
    title: "Apps de estudio y para qué sirven",
    media: inspirationMedia["tt-7509148365083397382"],
    note: "@studywzue. Carrusel lista de apps con hook directo. Formato educativo #studytok.",
    formatIds: ["x-razones"],
  },
  {
    id: "tt-7514943337355349253",
    kind: "post",
    platform: "TikTok",
    url: "https://www.tiktok.com/@joaquinscaffino/video/7514943337355349253",
    title: "Yo la noche antes del examen",
    media: inspirationMedia["tt-7514943337355349253"],
    note: "@joaquinscaffino. Reel relatable de estudiante pre-examen. Humor + identificación.",
  },
  {
    id: "tt-7504364442570820919",
    kind: "post",
    platform: "TikTok",
    url: "https://www.tiktok.com/@yami.gala/video/7504364442570820919",
    title: "Sitio secreto para usar IAs gratis — CTA comentá IA",
    media: inspirationMedia["tt-7504364442570820919"],
    note: "@yami.gala. Lead magnet con promesa fuerte + comentario para el link.",
  },
  {
    id: "tt-7510637747049172231",
    kind: "post",
    platform: "TikTok",
    url: "https://www.tiktok.com/@nickystudy12/photo/7510637747049172231",
    title: "Si no te esfuerzas, ¿con qué cara hablas de tus sueños?",
    media: inspirationMedia["tt-7510637747049172231"],
    note: "@nickystudy12. Carrusel motivacional estética study + frase dura.",
  },
  {
    id: "tt-7496185401934236933",
    kind: "post",
    platform: "TikTok",
    url: "https://www.tiktok.com/@adrian.sanabria2/photo/7496185401934236933",
    title: "Apps que nadie te dice que debes usar (estudiantes)",
    media: inspirationMedia["tt-7496185401934236933"],
    note: "@adrian.sanabria2. Carrusel con hook de curiosidad + setup aesthetic azul.",
    formatIds: ["x-razones"],
  },
  {
    id: "tt-7522914416019492114",
    kind: "post",
    platform: "TikTok",
    url: "https://www.tiktok.com/@daily__focus/photo/7522914416019492114",
    title: "No más lujuria — meme de disciplina",
    media: inspirationMedia["tt-7522914416019492114"],
    note: "@daily__focus. Carrusel meme/pop culture para foco y hábitos.",
  },
  {
    id: "tt-7509150445533793544",
    kind: "post",
    platform: "TikTok",
    url: "https://www.tiktok.com/@peternursing/photo/7509150445533793544",
    title: "Mientras tú duermes, alguien más está estudiando",
    media: inspirationMedia["tt-7509150445533793544"],
    note: "@peternursing. Carrusel motivación dura + aesthetic nocturno de estudio.",
  },
  {
    id: "tt-7488162731695115526",
    kind: "post",
    platform: "TikTok",
    url: "https://www.tiktok.com/@maurodamian.ar/video/7488162731695115526",
    title: "Comentarios falsos (o no) para tus videos",
    media: inspirationMedia["tt-7488162731695115526"],
    note: "@maurodamian.ar. Reel tutorial de hack de engagement/edición para creadores.",
    formatIds: ["captura-chat"],
  },
  {
    id: "tt-7489096856891444486",
    kind: "post",
    platform: "TikTok",
    url: "https://www.tiktok.com/@studyv.tok/video/7489096856891444486",
    title: "Go study — motivación #studytok",
    media: inspirationMedia["tt-7489096856891444486"],
    note: "@studyv.tok. Reel corto de disciplina y estudio con app Focus Tree.",
  },
  {
    id: "tt-7459852812785028374",
    kind: "post",
    platform: "TikTok",
    url: "https://www.tiktok.com/@ivanstudies/video/7459852812785028374",
    title: "Tip de productividad útil para estudiantes",
    media: inspirationMedia["tt-7459852812785028374"],
    note: "@ivanstudies. Reel con tip práctico + aesthetic universitario.",
  },
  {
    id: "tt-7495911638357282054",
    kind: "post",
    platform: "TikTok",
    url: "https://www.tiktok.com/@sebairuss/video/7495911638357282054",
    title: "Cómo encontrar ideas de contenido — CTA Idea",
    media: inspirationMedia["tt-7495911638357282054"],
    note: "@sebairuss. Reel para creadores: dolor de ideas + lead magnet por comentario.",
  },
  {
    id: "tt-7502235459695709448",
    kind: "post",
    platform: "TikTok",
    url: "https://www.tiktok.com/@estudio1252/photo/7502235459695709448",
    title: "Cómo estudiar para cada materia",
    media: inspirationMedia["tt-7502235459695709448"],
    note: "@estudio1252. Carrusel por materia (biología, mate, inglés). Estructura lista educativa.",
    formatIds: ["x-senales"],
  },
  {
    id: "tt-7493633424176024838",
    kind: "post",
    platform: "TikTok",
    url: "https://www.tiktok.com/@lu_boratti/video/7493633424176024838",
    title: "Referencia de estudio — @lu_boratti",
    media: inspirationMedia["tt-7493633424176024838"],
    note: "@lu_boratti. Reel #studytok. Guardado como referencia de formato y ritmo.",
  },
  {
    id: "x-2093392331466576105",
    kind: "post",
    platform: "X",
    url: "https://x.com/julesnewland/status/2093392331466576105",
    title: "Sumá IG, TikTok y X a Google Search Console",
    postText:
      "Recomiendo agregar la cuenta de Instagram, Tiktok y X a Google search console. Te muestra el trafico que te llega desde google por contenido generado en cada red. Se empieza a medir desde el día que lo agregas así que es clave sumarlo lo antes posible.",
    author: "Jules Newland (EXTRA) @julesnewland",
    media: inspirationMedia["x-2093392331466576105"],
    note: "@julesnewland. Tip de medición: tráfico desde Google por contenido en cada red. Acción rápida con alto ROI.",
  },
  {
    id: "ig-dv-kzi6fs0i",
    kind: "post",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DV-Kzi6Fs0I/",
    title: "6 capturas que los billonarios no quieren que veas",
    media: inspirationMedia["ig-dv-kzi6fs0i"],
    note: "@finanspace_. Carrusel con hook de curiosidad + figuras conocidas. Formato lista con tensión.",
    formatIds: ["x-razones", "titular-con-dato"],
  },
  {
    id: "ig-dv89vvkeqpq",
    kind: "post",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DV89VvKEQpq/",
    title: "Números que todo founder debería saber de memoria",
    media: inspirationMedia["ig-dv89vvkeqpq"],
    note: "@dylanrosemberg. Carrusel “guardá esto” con métricas clave sin abrir dashboard.",
  },
  {
    id: "ig-dvwivddjeix",
    kind: "post",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DVwIVDdjeIX/",
    title: "Impacto real de la IA en el trabajo — CTA comentá AI",
    media: inspirationMedia["ig-dvwivddjeix"],
    note: "@crece30x. Carrusel con dato de Anthropic + lead magnet por comentario.",
  },
  {
    id: "ig-dvtlkcjdr-7",
    kind: "post",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DVtLKCjDr-7/",
    title: "5 herramientas de AI que aceleraron el trabajo del equipo",
    media: inspirationMedia["ig-dvtlkcjdr-7"],
    note: "@dylanrosemberg. Lista de herramientas con beneficio concreto por ítem.",
    formatIds: ["x-razones"],
  },
  {
    id: "ig-dvumfteakpw",
    kind: "post",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DVuMfTeAKPw/",
    title: "Cómo aparecer cuando alguien le pregunta a la AI — 3 pasos",
    media: inspirationMedia["ig-dvumfteakpw"],
    note: "@dylanrosemberg. Reel educativo con CTA guardar. SEO/GEO para respuestas de IA.",
  },
  {
    id: "ig-dvqmi6wjlur",
    kind: "post",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DVqmi6wjlUr/",
    title: "Lead magnet — Comentá IA",
    media: inspirationMedia["ig-dvqmi6wjlur"],
    note: "@ramiro.cubria. Carrusel con CTA por comentario para entregar recurso.",
  },
  {
    id: "ig-duzxeg3akql",
    kind: "post",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DUzXEg3AKQL/",
    title: "La teoría de los cuatro quemadores",
    media: inspirationMedia["ig-duzxeg3akql"],
    note: "@soyoswalvidal. Carrusel tipo hilo: hook con nombres + concepto con metáfora visual.",
  },
  {
    id: "ig-dtvcz_zjmf4",
    kind: "post",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DTvCz_ZjMf4/",
    title: "Mejorar en tu negocio es disciplina y enfoque — reel",
    media: inspirationMedia["ig-dtvcz_zjmf4"],
    note: "@kengmemes. Reel motivacional B2B con mensaje de proceso constante.",
  },
  {
    id: "ig-dubnppmki4r",
    kind: "post",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DUBnPpmki4r/",
    title: "Elegí el mejor modelo de AI para cada pregunta — Perplexity",
    media: inspirationMedia["ig-dubnppmki4r"],
    note: "@perplexity. Carrusel de producto: beneficio claro por slide, copy sobrio.",
  },
  {
    id: "ig-ds3ckxoatgn",
    kind: "post",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DS3CkxoATgn/",
    title: "Comentá MÉTODO — lead magnet ecodiem",
    media: inspirationMedia["ig-ds3ckxoatgn"],
    note: "@ecodiem_academy. Carrusel con CTA por palabra clave en comentarios.",
  },
  {
    id: "ig-dqiw7y3j56m",
    kind: "post",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DQIW7Y3j56M/",
    title: "Guía para generar ideas de contenido con ChatGPT",
    media: inspirationMedia["ig-dqiw7y3j56m"],
    note: "@thefeedstrategy. Reel tutorial breve de content marketing con IA.",
  },
  {
    id: "ig-dflxkrusekm",
    kind: "post",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DFlxkrusEkm/",
    title: "Tip de edición: intro, mitad, final + stock",
    media: inspirationMedia["ig-dflxkrusekm"],
    note: "@dzntomi. Reel con hack de producción para grabar menos y editar más.",
  },
  {
    id: "ig-dhxkhfwmknz",
    kind: "post",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DHXKhfWMkNz/",
    title: "Post personal brand — manual de manifestación",
    media: inspirationMedia["ig-dhxkhfwmknz"],
    note: "@erinmuniz_. Imagen única con tono liviano + CTA al perfil. Referencia de voz personal.",
  },
  {
    id: "ig-dzyc2hupxzl",
    kind: "post",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DZyC2hupXZL/",
    title: "4 requisitos legales obligatorios para tu app SaaS",
    media: inspirationMedia["ig-dzyc2hupxzl"],
    note: "@hey.canter. Reel educativo B2B con hook de riesgo legal. Formato talking head + título directo.",
    formatIds: ["green-screen"],
  },
  {
    id: "ig-dzwemsejrhi",
    kind: "post",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DZWEmSEjRHI/",
    title: "3 marcas que hacen todo bien en Meta Ads",
    media: inspirationMedia["ig-dzwemsejrhi"],
    note: "@hey.canter. Carrusel lista con hook “deberías espiar”. Buen formato para análisis de referentes.",
    formatIds: ["x-razones"],
  },
  {
    id: "ig-dxzrrgldl1h",
    kind: "post",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DXzrrGlDl1H/",
    title: "18 documentos esenciales que toda startup debería tener",
    media: inspirationMedia["ig-dxzrrgldl1h"],
    note: "@hey.canter. Carrusel “guardá este post” con lista larga. Estructura educativa + autoridad.",
    formatIds: ["x-razones"],
  },
  {
    id: "ig-dwm-0qdeshk",
    kind: "post",
    platform: "Instagram",
    url: "https://www.instagram.com/p/DWm-0QdEShK/",
    title: "Teaser de producto Canter — lanzamiento con expectativa",
    media: inspirationMedia["ig-dwm-0qdeshk"],
    note: "@hey.canter. Carrusel de anuncio con build-up (“lo prometido es deuda”). Referencia de cómo presentan producto propio.",
  },
  {
    id: "tt-7523038791448268088",
    kind: "post",
    platform: "TikTok",
    url: "https://www.tiktok.com/@florentina.okk/video/7523038791448268088",
    title: "Motivación para estudiar — frases y mentalidad",
    media: inspirationMedia["tt-7523038791448268088"],
    note: "@florentina.okk. Video motivacional #studytok. Hook emocional y formato de frases para nicho estudiantes.",
  },
  {
    id: "tt-7530401573659233542",
    kind: "post",
    platform: "TikTok",
    url: "https://www.tiktok.com/@study.withmaca/photo/7530401573659233542",
    title: "Tips para estudiar cansada — carrusel con tips",
    media: inspirationMedia["tt-7530401573659233542"],
    note: "@study.withmaca. Carrusel numerado (descansar, etc.) con estética pop culture. Buen ejemplo de lista útil + identidad visual.",
    formatIds: ["x-razones"],
  },
  {
    id: "tt-7681117957874814216",
    kind: "post",
    platform: "TikTok",
    url: "https://www.tiktok.com/@nofeedback__/video/7681117957874814216",
    title: "Antes de generar imágenes con IA, tené las ideas claras — ep. 02",
    media: inspirationMedia["tt-7681117957874814216"],
    note: "@nofeedback__. Serie sobre proceso creativo con IA antes de producir.",
  },
  {
    id: "tt-7678305308300594439",
    kind: "post",
    platform: "TikTok",
    url: "https://www.tiktok.com/@tp_contentmanager/photo/7678305308300594439",
    title: "Si tu contenido solo intenta vender, perdés oportunidades",
    media: inspirationMedia["tt-7678305308300594439"],
    note: "Carrusel de @tp_contentmanager. Estructura identificar → curiosidad → conversación.",
  },
  {
    id: "tt-7646606156692999442",
    kind: "post",
    platform: "TikTok",
    url: "https://www.tiktok.com/@tomastorresi.ads/video/7646606156692999442",
    title: "Anuncio de imagen para ecommerce — Meta Ads",
    media: inspirationMedia["tt-7646606156692999442"],
    note: "@tomastorresi.ads. Referencia de formato/creativo para pauta en ecommerce.",
  },
  {
    id: "tt-7628369212066598164",
    kind: "post",
    platform: "TikTok",
    url: "https://www.tiktok.com/@zelunoapp/video/7628369212066598164",
    title: "Qué fácil es hacer ADS con IA — Zeluno",
    media: inspirationMedia["tt-7628369212066598164"],
    note: "@zelunoapp. Producto SaaS mostrando flujo de creación de ads con IA.",
  },
  {
    id: "tt-7612349885765012756",
    kind: "post",
    platform: "TikTok",
    url: "https://www.tiktok.com/@laulodel_/video/7612349885765012756",
    title: "Mejorá tus fondos con IA — tutorial de edición",
    media: inspirationMedia["tt-7612349885765012756"],
    note: "@laulodel_. Tutorial práctico de edición con IA para fondos.",
  },
  {
    id: "tt-7659480267479993621",
    kind: "post",
    platform: "TikTok",
    url: "https://www.tiktok.com/@juanbadal/video/7659480267479993621",
    title: "Cómo minificamos las redes de Minificando",
    media: inspirationMedia["tt-7659480267479993621"],
    note: "Video largo (~3 min) de @juanbadal. Referencia de formato talking head y narrativa sobre simplificar redes.",
  },
  {
    id: "tt-7630167547035340053",
    kind: "post",
    platform: "TikTok",
    url: "https://www.tiktok.com/@franco.zanolin/photo/7630167547035340053?_r=1&_t=ZS-99am7s0Ghev",
    title: "9 apps para construir startup con IA",
    media: inspirationMedia["tt-7630167547035340053"],
    note: "Carrusel de @franco.zanolin. Lista de herramientas con IA para founders.",
  },
];
